[Config]
# If this is set to false, it will use the email to display name method.
bUseConfigDisplayName=false
# Your fortnite display name (will only be used if the property above is set to true).
displayName=LawinServer

[Profile]
# If this is set to true, every BR and StW seasonal quest will be on complete. Supported for Battle Royale from Season 3 to Season 40 and for Save the World from Season 2 to Season X & Season 24.
bCompletedSeasonalQuests=false
# If this is set to true, you will receive all founder's pack rewards upon logging into StW if the account didn't claim them yet.
bGrantFoundersPacks=false
# If this is set to true, all Save the World events will be displayed in lobby.
bAllSTWEventsActivated=false

[GameServer]
# Matchmaker gameserver config, you can use this to connect to gameservers like rift (titanium), fortmp, etc... (they have to be hosting though).

# IP the matchmaker will use upon join.
ip=127.0.0.1
# PORT the matchmaker will use upon join.
port=7777

[Events]
# All dates must be specified using ISO date format only (UTC).
# *Requires a Gameserver connected to this LawinServer backend. Clients can use other backends.

## The Rocket Start event. (v4.5 Only)*

# If this is set to true, the event countdown will appear next to
# the Rocket and the event will start at the date below.
bEnableGeodeEvent=false
geodeEventStartDate=2020-01-01T00:00:00.000Z
# If this is set to true, the Crack will stay in the sky AFTER the event.
# The crack will fully expand after ~13.6 real days after the Rocket event start date.
bEnableCrackInTheSky=false

## Eight mini-events which took the following objects from the map: (v4.5 Only)*
## 1. Lonely Lodge Sign, 2. Motel Sign, 3. Tomatohead Mascot, 4. NOMS Sign, 5. Durr Burger Mascot
## and brought the following objects to the map:
## 6. Ship Anchor, 7. Horse Carriage, 8. Dinosaur Skeleton.
## To see the exact locations, you can check out this video: https://youtu.be/NXL7rkiJVqM

# If this is set to true, the blue rift effects will appear at places mentioned above.
bEnableS4OddityPrecursor=false
# If this is set to true, the mini-events will begin to start. (Adjust the options below)
bEnableS4OddityExecution=false
# Start date for the Season 4 mini-events. If you have the Rocket event enabled as
# well, then set this date to at least 4 minutes after your Rocket start date.
S4OddityEventStartDate=2020-01-01T00:00:00.000Z
# Time (in minutes) after which another mini-event (1-8) will occur.
# If set to 0, all mini-events will happen at once.
S4OddityEventsInterval=0

## Tomatohead Comeback mini-event. (v5.21 Only)*

# When set to true, the blue rift effects will start appearing on
# top of the Tomato Town restaurant at the date specified below.
bEnableS5OddityPrecursor=false
S5OddityPrecursorDate=2020-01-01T00:00:00.000Z
# When set to true, Tomatohead will be rifted back to Tomato Town at the date specified below.
bEnableS5OddityExecution=false
S5OddityExecutionDate=2020-01-01T00:00:00.000Z

## Lightning from the sky Crack and Cube Spawning Event. (v5.30 Only)*

# When set to true, the crack will start shooting lightning bolts destroying
# cacti and eventually spawn the cube on the date specified below.
bEnableCubeLightning=false
cubeSpawnDate=2020-01-01T00:00:00.000Z

## Blockbuster Contest winner video at Risky Reels event. (v5.30 Only)*
bEnableBlockbusterRiskyEvent=false

## Cube melting in Loot Lake event. (v5.41 Only)*

# When set to true, the cube will fall into Loot Lake and start melting on the date specified below.
# After the event, Loot Lake will remain purple in new matches.
bEnableCubeLake=false
cubeLakeDate=2020-01-01T00:00:00.000Z

## Water level in Chapter 2 Season 3

# There are 8 water levels, 0 -> 7. Lower number = lower water.
# If a number outside of 0 -> 6 is input, it will use water level 7
waterLevel=0

## Chapter 2 Sesaon 4

# The date specifies when galactus will be at 100% progress
bEnableGalactus=true
galactusArriveDate=2026-06-04T00:00:00.000Z

## Chapter 2 Season 5 Portals
bPortalCherry=true
bPortalKepler=true
bPortalMainframe=true
bPortalNightmare=true
bPortalSkirmish=true
bPortalSmallFry=true
bPortalTyphoon=true
bPortalWombat=true

## Chapter 2 Season 7 stuff

# Changed the abduction poi based on the build.
# 17.30 = Slurpy, 17.40 = Coral, 17.50 = Corny
bAbductPOI=true

## Chapter 4 Season 4

# Teasers for Season OG
# 1 = Time machine in Kado Thornes basement.
# 2 = Time machine + OG Props in Frenzy Fields.
# 3 = Teaser signs in Mega City and Time machine + OG Props leave Frenzy Fields.
ogTeaseStage=2

[BattleBus]
# false = Picks battle bus skin based on the build
bForceDefault=false

[Season9]
bEnableBirthday=true

# 0 = Nothing, 1 - 15 = A duck with 1 million HP spawns somewhere
bigDuckyStage=1

bEnableCattusDoggus=false
cattusDoggusStartDate=2026-06-29T18:02:00.000Z

[Season10]
# TUTORIAL: How to disable NightNight!
# 1. Go to %LOCALAPPDATA%/FortniteGame/Saved/Config/WindowsClient/GameUserSettings.ini
# 2. Change the line "UserPreferredFrontend=NoBernieNo" to "UserPreferredFrontend="
# 3. Save and Exit file.

# true = Play The End Event (Lobby Version)
bEnableNightNight=false

# true = At the date below, The End Event starts.
bEnableNightNightEvent=false
eventNightNightStartDate=2026-06-29T17:35:00.000Z

[Season12]
# 0 = Nothing
# 1 = Astroworld in sky, far away
# 2 = Astroworld in sky, much closer
astroSkyPhase=2

# 0 = Default
# 1 = Bubbles?
# 2 = Open
agencyHatchStage=2

# 0 = None, 1 to 3 = cables
cableStage=3

# 0 = Default
# 1 = Active
# 2 = Destroyed
deviceStage=1

bEnableWaterStorm=true
